version: "2"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      - Test=test
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes: 
      - /var/lib/mysql:/var/lib/mysql
  eureka:
    image: eureka
    ports:
      - 8761:8761
  config-server:
    image: config-server
    ports:
      - 8888:8888  
    environment:
      - SPRING_PROFILES_ACTIVE=native 
    volumes: 
      - ./config_files:/tmp
